# Generated by Django 3.1.7 on 2021-03-07 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='user',
            new_name='owner',
        ),
    ]
