# Generated by Django 3.1.7 on 2021-03-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(),
        ),
    ]
