# Generated by Django 3.1.7 on 2021-03-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20210308_1438'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set(),
        ),
    ]
