# Generated by Django 3.1.7 on 2021-03-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_auto_20210312_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
